services:

  nginx:
    build: ./nginx/
    ports:
      - 80:80
    image: nginx_c2
    container_name: c2_web
    volumes:
        - ./:/var/www/html/

  php:
    build: 
      context: ./
      dockerfile: ./php-fpm/Dockerfile
    expose:
      - 9000
    image: php_fpm_c2
    container_name: c2_php_fpm
    volumes:
      - ./:/var/www/html/

  db:
    build: ./mysql/
    image: mysql_c2
    container_name: c2_db
    command: --explicit_defaults_for_timestamp=1
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/controle.sql:/docker-entrypoint-initdb.d/controle.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"

volumes:
  db_data: